### ISSUE TITLE
Cursor parsing maps with integer values fails

### ISSUE THREAD

**Issue by geofffranks** [jhunt/tree#2]
If you have a map with a numeric key, resolve/glob think that the datastructure must be an array, rather than a map, and it fails to find your key. Or put another way, when processing a map, resolve/glob do not look at keys that are numeric values, or stringified forms of numeric values.

May only be an issue when processing map[string]interface{} and map[interface{}]interface{} works?

**Comment by jhunt** [comment]
I believe this is only an issue when dealing with `interface{}` keys, which tree.Cursor doesn't do.  Will submit PR to have the confirming test verified independently.
